[package]
name = "Voxelized3D-Rust"
version = "0.0.1"
authors = ["russoul <russoulmc@gmail.com>"]
build = "build.rs"
links = "rsutil"

[dependencies]
libc = "0.2.0"
generic-array = "0.9.0"
ansi_term = "0.10.2"
nalgebra = "0.13.1"
typenum = "1.9.0"
alga = "0.5.2"
time = "0.1.39"
num = "*"
rand = "0.4"
noise = "*"

[build-dependencies]
cc = "1.0"
cmake = "0.1"

