[package]
name = "Voxelized2D-Rust"
version = "0.0.1"
authors = ["russoul <russoulmc@gmail.com>"]
build = "build.rs"
links = "rsutil"

[dependencies]
libc = "0.2.0"
generic-array = "0.9.0"
num = "*"
ansi_term = "*"

[build-dependencies]
cc = "1.0"

